# Generated by Django 3.2.4 on 2021-07-22 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Complete by')),
                ('charm', models.CharField(choices=[('S', 'Started'), ('H', 'Halfway'), ('D', 'Done')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Comb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(max_length=100)),
                ('goal_description', models.TextField(max_length=1000)),
                ('comb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.comb')),
            ],
        ),
    ]
