# Generated by Django 3.2.4 on 2021-07-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comb',
            name='atchieve_by',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='comb',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
