# Generated by Django 3.2.4 on 2021-07-21 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210719_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(max_length=100)),
                ('goal_description', models.TextField(max_length=1000)),
                ('goal_atchieve_by', models.DateField(null=True)),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Charm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('charm', models.CharField(choices=[('S', 'Started'), ('H', 'Halfway'), ('D', 'Done')], default='S', max_length=1)),
                ('comb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.comb')),
            ],
        ),
    ]
